### ISSUE TITLE
support longer than 2m timeouts

### ISSUE THREAD

**Issue by bengreenier** [anastasiia-zolochevska/signaling-server#4]
per https://nodejs.org/api/http.html#http_server_timeout the default timeout for a socket is set to `2m` - since we rely heavily on long polling (and in fact, expect that we'll have sockets pending for some time) it may make sense to increase this value to reduce reconnects.

Either way, we should likely document this behavior.

**Comment by anastasiia-zolochevska** [comment]
It seems to be a bug specific to deployment to Azure Web apps. Timeout happens on TCP level and for unknown reason it results in 500 error on HTTP level.  We will report this to Azure App Services product team. Meanwhile recommendation is to create a temporary workaround to reconnect to signaling server from client side after hitting this error.
